package com.wondersgroup.infopub.dao;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import com.wondersgroup.infopub.bean.InfopubPsource;

/**
 * 发布源
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubPsourceDao {

    private Connection con = null;

    public InfopubPsourceDao() {
    }

    public InfopubPsourceDao(Connection con) {
        this.con = con;
    }

    public void add(InfopubPsource info) {
        String sql = "insert into INFOPUB_PSOURCE(ST_PSOURCE_ID, ST_PSOURCE_NAME, NM_OFFLINE, ST_ATTACH_ID, ST_USER_ID, DT_CREATE, DT_UPDATE, ST_DESC, ST_WORKSPACE_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStPsourceId(),
            info.getStPsourceName(),
            info.getNmOffline(),
            info.getStAttachId(),
            info.getStUserId(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc(),
            info.getStWorkspaceId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(InfopubPsource info) {
        String sql = "update INFOPUB_PSOURCE set ST_PSOURCE_NAME = ?, NM_OFFLINE = ?, ST_ATTACH_ID = ?, ST_USER_ID = ?, DT_CREATE = ?, DT_UPDATE = ?, ST_DESC = ?, ST_WORKSPACE_ID = ? where ST_PSOURCE_ID = ?";
        Object[] obj = {
            info.getStPsourceName(),
            info.getNmOffline(),
            info.getStAttachId(),
            info.getStUserId(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc(),
            info.getStWorkspaceId(),
            info.getStPsourceId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update INFOPUB_PSOURCE set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from INFOPUB_PSOURCE";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stPsourceId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stPsourceId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_PSOURCE_ID", Condition.OT_EQUAL, stPsourceId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stPsourceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_PSOURCE_ID", Condition.OT_EQUAL, stPsourceId));
        delete(conds);
    }

    public PaginationArrayList<InfopubPsource> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_PSOURCE", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "INFOPUB_PSOURCE", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<InfopubPsource> pal = new PaginationArrayList<InfopubPsource>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            InfopubPsource info = new InfopubPsource();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<InfopubPsource> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_PSOURCE", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "INFOPUB_PSOURCE", "*", conds, suffix);
        }
        ArrayList<InfopubPsource> al = new ArrayList<InfopubPsource>();
        while (rs.next()) {
            InfopubPsource info = new InfopubPsource();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(InfopubPsource info, RecordSet rs){
        info.setStPsourceId(rs.getOriginalString("ST_PSOURCE_ID"));
        info.setStPsourceName(rs.getOriginalString("ST_PSOURCE_NAME"));
        info.setNmOffline(rs.getBigDecimal("NM_OFFLINE"));
        info.setStAttachId(rs.getOriginalString("ST_ATTACH_ID"));
        info.setStUserId(rs.getOriginalString("ST_USER_ID"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setDtUpdate(rs.getTimestamp("DT_UPDATE"));
        info.setStDesc(rs.getOriginalString("ST_DESC"));
        info.setStWorkspaceId(rs.getOriginalString("ST_WORKSPACE_ID"));
    }

	public InfopubPsource get(String stPsourceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_PSOURCE_ID", Condition.OT_EQUAL, stPsourceId));
        List<InfopubPsource> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
