package com.wondersgroup.infopub.dao;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import com.wondersgroup.infopub.bean.InfopubWorkspaceUser;

/**
 * 信息发布用户关联空间
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubWorkspaceUserDao {

    private Connection con = null;

    public InfopubWorkspaceUserDao() {
    }

    public InfopubWorkspaceUserDao(Connection con) {
        this.con = con;
    }

    public void add(InfopubWorkspaceUser info) {
        String sql = "insert into INFOPUB_WORKSPACE_USER(ST_USER_ID, ST_WORKSPACE_ID, NM_ORDER, ST_EXT1, ST_EXT2) values (?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStUserId(),
            info.getStWorkspaceId(),
            info.getNmOrder(),
            info.getStExt1(),
            info.getStExt2()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(InfopubWorkspaceUser info) {
        String sql = "update INFOPUB_WORKSPACE_USER set NM_ORDER = ?, ST_EXT1 = ?, ST_EXT2 = ? where ST_USER_ID = ? and ST_WORKSPACE_ID = ?";
        Object[] obj = {
            info.getNmOrder(),
            info.getStExt1(),
            info.getStExt2(),
            info.getStUserId(),
            info.getStWorkspaceId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update INFOPUB_WORKSPACE_USER set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from INFOPUB_WORKSPACE_USER";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stUserId, String[] stWorkspaceId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stUserId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_USER_ID", Condition.OT_EQUAL, stUserId[i]));
            subconds.add(new Condition("ST_WORKSPACE_ID", Condition.OT_EQUAL, stWorkspaceId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stUserId, String stWorkspaceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_USER_ID", Condition.OT_EQUAL, stUserId));
        conds.add(new Condition("ST_WORKSPACE_ID", Condition.OT_EQUAL, stWorkspaceId));
        delete(conds);
    }

    public PaginationArrayList<InfopubWorkspaceUser> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_WORKSPACE_USER", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "INFOPUB_WORKSPACE_USER", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<InfopubWorkspaceUser> pal = new PaginationArrayList<InfopubWorkspaceUser>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            InfopubWorkspaceUser info = new InfopubWorkspaceUser();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<InfopubWorkspaceUser> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_WORKSPACE_USER", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "INFOPUB_WORKSPACE_USER", "*", conds, suffix);
        }
        ArrayList<InfopubWorkspaceUser> al = new ArrayList<InfopubWorkspaceUser>();
        while (rs.next()) {
            InfopubWorkspaceUser info = new InfopubWorkspaceUser();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(InfopubWorkspaceUser info, RecordSet rs){
        info.setStUserId(rs.getOriginalString("ST_USER_ID"));
        info.setStWorkspaceId(rs.getOriginalString("ST_WORKSPACE_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setStExt1(rs.getOriginalString("ST_EXT1"));
        info.setStExt2(rs.getOriginalString("ST_EXT2"));
    }

	public InfopubWorkspaceUser get(String stUserId, String stWorkspaceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_USER_ID", Condition.OT_EQUAL, stUserId));
        conds.add(new Condition("ST_WORKSPACE_ID", Condition.OT_EQUAL, stWorkspaceId));
        List<InfopubWorkspaceUser> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
