package com.wondersgroup.infopub.dao;

import java.sql.Connection;

import org.springframework.stereotype.Repository;

/**
 * 信息发布用户空间
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubWorkspaceDaoExt extends InfopubWorkspaceDao{

    @SuppressWarnings("unused")
	private Connection con = null;

    public InfopubWorkspaceDaoExt() {
    }

    public InfopubWorkspaceDaoExt(Connection con) {
        this.con = con;
    }
}
