package com.wondersgroup.infopub.dao;

import java.sql.Connection;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import com.wondersgroup.infopub.bean.InfopubDeviceLog;

/**
 * 设备日志记录
 * 
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubDeviceLogDaoExt extends InfopubDeviceLogDao {

	private Connection con = null;

	public InfopubDeviceLogDaoExt() {
	}

	public InfopubDeviceLogDaoExt(Connection con) {
		this.con = con;
	}

	public PaginationArrayList<InfopubDeviceLog> queryDeviceName(
			Conditions conds, String suffix, int pageSize, int currentPage) {
		RecordSet rs;
		String content = "IDL.ST_DEVICE_LOG_ID, IDL.DT_CREATE,	IDL.ST_ACTION,	IDL.ST_DEVICE_ID,	IDL.ST_EXCEPTION,	IDL.ST_EXT2, "
				+ " IDL.ST_LEVEL, IDL.ST_LINE, IDL.ST_LOCATION,	IDL.ST_LOGGER,	IDL.ST_METHOD,	IDL.ST_MSG,	IDL.ST_OPERAND, "
				+ " IDL.ST_OPERATOR,	IDL.ST_THREAD,	IDI.ST_DEVICE_NAME AS ST_EXT1";
		String table = "INFOPUB_DEVICE_LOG IDL LEFT JOIN INFOPUB_DEVICE_INFO IDI ON IDL.ST_DEVICE_ID = IDI.ST_DEVICE_ID";
		if (con == null) {
			rs = SQL.query(table, content, conds, suffix, pageSize,
					currentPage);
		} else {
			rs = SQL.query(con, table, content, conds, suffix,
					pageSize, currentPage);
		}
		PaginationArrayList<InfopubDeviceLog> pal = new PaginationArrayList<InfopubDeviceLog>(
				rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
		while (rs.next()) {
			InfopubDeviceLog info = new InfopubDeviceLog();
			setProperties(info, rs);
			pal.add(info);
		}
		return pal;
	}
}
