package com.wondersgroup.infopub.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;
import wfc.service.log.Log;

import com.wondersgroup.business.bean.SelmQueryHis;
import com.wondersgroup.infopub.bean.InfopubDeviceInfo;
import com.wondersgroup.infopub.bean.InfopubDeviceInfoHis;
import com.wondersgroup.infopub.bean.InfopubDeviceInfoExt;
import com.wondersgroup.infopub.bean.InfopubDeviceInfoMap;

/**
 * 信息设备
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubDeviceInfoHisDao {

    private Connection con = null;

    public InfopubDeviceInfoHisDao() {
    }

    public InfopubDeviceInfoHisDao(Connection con) {
        this.con = con;
    }

    public void add(InfopubDeviceInfoHis info) {
        String sql = "insert into INFOPUB_DEVICE_INFO_HIS(ST_DEVICE_ID, ST_DEVICE_NAME, ST_DEVICE_CODE, ST_DEVICE_IP, ST_DEVICE_MAC, ST_DEVICE_ADDRESS, ST_TYPE_ID, NM_IS_HOST, NM_ORDER, NM_INTERVAL, NM_RECOVER, NM_DOWN_TRY, NM_NOTIFICATION, NM_LNG, NM_LAT, NM_ONLINE, ST_CHANNEL, ST_CONFIG_ID, NM_SDTYPE, ST_USER_ID, ST_AREA_ID, ST_ADDRESS_ID, ST_CERT_KEY, DT_CREATE, DT_UPDATE, ST_DESC, ST_ORGAN_ID, ST_STATE) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStDeviceId(),
            info.getStDeviceName(),
            info.getStDeviceCode(),
            info.getStDeviceIp(),
            info.getStDeviceMac(),
            info.getStDeviceAddress(),
            info.getStTypeId(),
            info.getNmIsHost(),
            info.getNmOrder(),
            info.getNmInterval(),
            info.getNmRecover(),
            info.getNmDownTry(),
            info.getNmNotification(),
            info.getNmLng(),
            info.getNmLat(),
            info.getNmOnline(),
            info.getStChannel(),
            info.getStConfigId(),
            info.getNmSdtype(),
            info.getStUserId(),
            info.getStAreaId(),
            info.getStAddressId(),
            info.getStCertKey(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc(),  
            info.getStOrganId(),
            info.getStState()
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(InfopubDeviceInfoHis info) {
        String sql = "update INFOPUB_DEVICE_INFO_HIS set ST_DEVICE_NAME = ?, ST_DEVICE_CODE = ?, ST_DEVICE_IP = ?, ST_DEVICE_MAC = ?, ST_DEVICE_ADDRESS = ?, ST_TYPE_ID = ?, NM_IS_HOST = ?, NM_ORDER = ?, NM_INTERVAL = ?, NM_RECOVER = ?, NM_DOWN_TRY = ?, NM_NOTIFICATION = ?, NM_LNG = ?, NM_LAT = ?, NM_ONLINE = ?, ST_CHANNEL = ?, ST_CONFIG_ID = ?, NM_SDTYPE = ?, ST_USER_ID = ?, ST_AREA_ID = ?, ST_ADDRESS_ID = ?, ST_CERT_KEY = ?, DT_CREATE = ?, DT_UPDATE = ?, ST_DESC = ? , ST_ORGAN_ID = ? , ST_STATE = ? where ST_DEVICE_ID = ?";
        Object[] obj = {
            info.getStDeviceName(),
            info.getStDeviceCode(),
            info.getStDeviceIp(),
            info.getStDeviceMac(),
            info.getStDeviceAddress(),
            info.getStTypeId(),
            info.getNmIsHost(),
            info.getNmOrder(),
            info.getNmInterval(),
            info.getNmRecover(),
            info.getNmDownTry(),
            info.getNmNotification(),
            info.getNmLng(),
            info.getNmLat(),
            info.getNmOnline(),
            info.getStChannel(),
            info.getStConfigId(),
            info.getNmSdtype(),
            info.getStUserId(),
            info.getStAreaId(),
            info.getStAddressId(),
            info.getStCertKey(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc(),
            info.getStOrganId(),
            info.getStDeviceId(),
            info.getStState()
            
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update INFOPUB_DEVICE_INFO_HIS set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    
    
    
   
    public int delete(Conditions conds) {
        String sql = "delete from INFOPUB_DEVICE_INFO_HIS";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

    public PaginationArrayList<InfopubDeviceInfoHis> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_DEVICE_INFO_HIS", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "INFOPUB_DEVICE_INFO_HIS", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<InfopubDeviceInfoHis> pal = new PaginationArrayList<InfopubDeviceInfoHis>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            InfopubDeviceInfoHis info = new InfopubDeviceInfoHis();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<InfopubDeviceInfoHis> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_DEVICE_INFO_HIS", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "INFOPUB_DEVICE_INFO_HIS", "*", conds, suffix);
        }
        ArrayList<InfopubDeviceInfoHis> al = new ArrayList<InfopubDeviceInfoHis>();
        while (rs.next()) {
            InfopubDeviceInfoHis info = new InfopubDeviceInfoHis();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(InfopubDeviceInfoHis info, RecordSet rs){
    	info.setStDeviceId(rs.getOriginalString("ST_DEVICE_ID"));
        info.setStDeviceName(rs.getOriginalString("ST_DEVICE_NAME"));
        info.setStDeviceCode(rs.getOriginalString("ST_DEVICE_CODE"));
        info.setStDeviceIp(rs.getOriginalString("ST_DEVICE_IP"));
        info.setStDeviceMac(rs.getOriginalString("ST_DEVICE_MAC"));
        info.setStDeviceAddress(rs.getOriginalString("ST_DEVICE_ADDRESS"));
        info.setStTypeId(rs.getOriginalString("ST_TYPE_ID"));
        info.setNmIsHost(rs.getBigDecimal("NM_IS_HOST"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setNmInterval(rs.getBigDecimal("NM_INTERVAL"));
        info.setNmRecover(rs.getBigDecimal("NM_RECOVER"));
        info.setNmDownTry(rs.getBigDecimal("NM_DOWN_TRY"));
        info.setNmNotification(rs.getBigDecimal("NM_NOTIFICATION"));
        info.setNmLng(rs.getBigDecimal("NM_LNG"));
        info.setNmLat(rs.getBigDecimal("NM_LAT"));
        info.setNmOnline(rs.getBigDecimal("NM_ONLINE"));
		info.setStConfigId(rs.getOriginalString("ST_CONFIG_ID"));
        info.setStChannel(rs.getOriginalString("ST_CHANNEL"));
        info.setNmSdtype(rs.getBigDecimal("NM_SDTYPE"));
        info.setStUserId(rs.getOriginalString("ST_USER_ID"));
        info.setStAreaId(rs.getOriginalString("ST_AREA_ID"));
        info.setStAddressId(rs.getOriginalString("ST_ADDRESS_ID"));
        info.setStCertKey(rs.getOriginalString("ST_CERT_KEY"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setDtUpdate(rs.getTimestamp("DT_UPDATE"));
        info.setStDesc(rs.getOriginalString("ST_DESC"));
        info.setStOrganId(rs.getOriginalString("ST_ORGAN_ID"));
        info.setStState(rs.getOriginalString("ST_STATE"));
    }

	public InfopubDeviceInfoHis get(String stDeviceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId));
        List<InfopubDeviceInfoHis> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }
	
	public InfopubDeviceInfoHis getCode(String stDeviceCode) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DEVICE_CODE", Condition.OT_EQUAL, stDeviceCode));
        List<InfopubDeviceInfoHis> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }
	
	public InfopubDeviceInfoHis getMac(String stDeviceMac) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DEVICE_MAC", Condition.OT_EQUAL, stDeviceMac));
        List<InfopubDeviceInfoHis> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }
	
	public List<InfopubDeviceInfo> wGetDevice(Conditions conds, String suffix) {
		RecordSet rs;
        String content = "idi.ST_DEVICE_ID,idi.ST_DEVICE_NAME,idi.ST_DEVICE_MAC,idi.ST_DEVICE_IP,ia.ST_LABEL,ia.ST_CITY,ia.ST_DISTRICT,ia.ST_STREET,ia.ST_ADDRESS,idt.ST_TYPE_NAME";
        String table = "infopub_device_info idi left join infopub_device_type idt on idt.ST_TYPE_ID = idi.ST_TYPE_ID "+
        			   "left join infopub_address ia on idi.ST_ADDRESS_ID = ia.ST_ADDRESS_ID "+
        			   "left join infopub_area iaa on idi.ST_AREA_ID = iaa.ST_AREA_ID "; 
        if (con == null) {
            rs = SQL.query(table, content, conds, suffix);
        } else {
            rs = SQL.query(con, table, content, conds, suffix);
        }
        List<InfopubDeviceInfo> al = new ArrayList<InfopubDeviceInfo>();
        InfopubDeviceInfo info = new InfopubDeviceInfo();
        while (rs.next()) {
        	info = new InfopubDeviceInfo();
        	info.setStDeviceId(rs.getOriginalString("ST_DEVICE_ID"));
        	info.setStDeviceName(rs.getOriginalString("ST_DEVICE_NAME"));
        	info.setStDeviceMac(rs.getOriginalString("ST_DEVICE_MAC"));
        	info.setStDeviceIp(rs.getOriginalString("ST_DEVICE_IP"));
        	info.setStAreaId(rs.getOriginalString("ST_LABEL"));
        	info.setStAddressId(rs.getOriginalString("ST_CITY"));
        	info.setStDeviceAddress(rs.getOriginalString("ST_DISTRICT"));
        	info.setStDesc(rs.getOriginalString("ST_STREET"));
        	info.setStConfigId(rs.getOriginalString("ST_ADDRESS"));
        	info.setStTypeId(rs.getOriginalString("ST_TYPE_NAME"));
        	al.add(info);
        }
        return al;
	}
	
	
	
}
