package com.wondersgroup.infopub.dao;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import com.wondersgroup.infopub.bean.InfopubOnoff;

/**
 * 设备开关机
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class InfopubOnoffDao {

    private Connection con = null;

    public InfopubOnoffDao() {
    }

    public InfopubOnoffDao(Connection con) {
        this.con = con;
    }

    public void add(InfopubOnoff info) {
        String sql = "insert into INFOPUB_ONOFF(ST_ONOFF_ID, ST_DEVICE_ID, ST_PTYPE, ST_ON_TIME, ST_OFF_TIME, ST_PERIOD, DT_ONOFF, DT_CREATE, DT_UPDATE, ST_DESC) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStOnoffId(),
            info.getStDeviceId(),
            info.getStPtype(),
            info.getStOnTime(),
            info.getStOffTime(),
            info.getStPeriod(),
            info.getDtOnoff(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(InfopubOnoff info) {
        String sql = "update INFOPUB_ONOFF set ST_DEVICE_ID = ?, ST_PTYPE = ?, ST_ON_TIME = ?, ST_OFF_TIME = ?, ST_PERIOD = ?, DT_ONOFF = ?, DT_CREATE = ?, DT_UPDATE = ?, ST_DESC = ? where ST_ONOFF_ID = ?";
        Object[] obj = {
            info.getStDeviceId(),
            info.getStPtype(),
            info.getStOnTime(),
            info.getStOffTime(),
            info.getStPeriod(),
            info.getDtOnoff(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStDesc(),
            info.getStOnoffId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update INFOPUB_ONOFF set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from INFOPUB_ONOFF";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stOnoffId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stOnoffId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_ONOFF_ID", Condition.OT_EQUAL, stOnoffId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stOnoffId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ONOFF_ID", Condition.OT_EQUAL, stOnoffId));
        delete(conds);
    }

    public PaginationArrayList<InfopubOnoff> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_ONOFF", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "INFOPUB_ONOFF", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<InfopubOnoff> pal = new PaginationArrayList<InfopubOnoff>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            InfopubOnoff info = new InfopubOnoff();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<InfopubOnoff> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("INFOPUB_ONOFF", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "INFOPUB_ONOFF", "*", conds, suffix);
        }
        ArrayList<InfopubOnoff> al = new ArrayList<InfopubOnoff>();
        while (rs.next()) {
            InfopubOnoff info = new InfopubOnoff();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(InfopubOnoff info, RecordSet rs){
        info.setStOnoffId(rs.getOriginalString("ST_ONOFF_ID"));
        info.setStDeviceId(rs.getOriginalString("ST_DEVICE_ID"));
        info.setStPtype(rs.getOriginalString("ST_PTYPE"));
        info.setStOnTime(rs.getOriginalString("ST_ON_TIME"));
        info.setStOffTime(rs.getOriginalString("ST_OFF_TIME"));
        info.setStPeriod(rs.getOriginalString("ST_PERIOD"));
        info.setDtOnoff(rs.getTimestamp("DT_ONOFF"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setDtUpdate(rs.getTimestamp("DT_UPDATE"));
        info.setStDesc(rs.getOriginalString("ST_DESC"));
    }

	public InfopubOnoff get(String stOnoffId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ONOFF_ID", Condition.OT_EQUAL, stOnoffId));
        List<InfopubOnoff> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
