let perjsonStr = []
if($.getConfigMsg.isCommunity == 'Y' || $.getConfigMsg.isCommunity == null || $.getConfigMsg.isCommunity ==  undefined) {
	perjsonStr = [{
		"stuffName": "上海市学生事务中心存档证明",
		"type": "JW_studentAffairsCenter",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "民办教育机构查询",
		"type": "JW_privateEducational",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "全市示范高中信息查询",
		"type": "JW_modelHighschool",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "中外合作办学信息查询",
		"type": "../JW_cooperateEducationInfo/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "小升初报名信息查询(公办、民办)",
		"type": "../JW_queryRegistrationInfo_XSC/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "幼升小报名信息查询(公办、民办)",
		"type": "../JW_queryRegistrationInfo_YSX/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "上海市计算机等级考试成绩查询",
		"type": "../JW_queryScoreOfNCRE/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "3岁以下幼儿托育服务机构查询",
		"type": "../JW_queryNurseryService/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "民办非学历培训机构查询",
		"type": "../JW_queryTrainingInstitutions/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}];
} else {
	perjsonStr = [{
		"stuffName": "上海市学生事务中心存档证明",
		"type": "JW_studentAffairsCenter",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "民办教育机构查询",
		"type": "JW_privateEducational",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "全市示范高中信息查询",
		"type": "JW_modelHighschool",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "中外合作办学信息查询",
		"type": "../JW_cooperateEducationInfo/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "小升初报名信息查询(公办、民办)",
		"type": "../JW_queryRegistrationInfo_XSC/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "幼升小报名信息查询(公办、民办)",
		"type": "../JW_queryRegistrationInfo_YSX/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "上海市计算机等级考试成绩查询",
		"type": "../JW_queryScoreOfNCRE/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "3岁以下幼儿托育服务机构查询",
		"type": "../JW_queryNurseryService/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}, {
		"stuffName": "民办非学历培训机构查询",
		"type": "../JW_queryTrainingInstitutions/index.html",
		"ywlx": "00",
		"img": "../libs/common/images/newIcon/JY.png",
	}];
}