package com.wondersgroup.business.dao;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.math.*;
import java.sql.*;
import java.util.*;
import wfc.facility.tool.autocode.*;
import wfc.service.database.*;

import org.springframework.stereotype.Repository;

import com.wondersgroup.business.bean.SelmAttach;

/**
 * 附件表
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class SelmAttachDao {

    private Connection con = null;

    public SelmAttachDao() {
    }

    public SelmAttachDao(Connection con) {
        this.con = con;
    }

    public void add(SelmAttach info) {
        String sql = "insert into SELM_ATTACH(ST_ATTACH_ID, ST_LINK_TABLE, ST_LINK_ID, ST_ATTACH_TYPE, ST_FILENAME, ST_FILE_SIZE, ST_FILE_TYPE, NM_ORDER, DT_CREATE, DT_UPDATE, ST_EXT1, ST_EXT2) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStAttachId(),
            info.getStLinkTable(),
            info.getStLinkId(),
            info.getStAttachType(),
            info.getStFilename(),
            info.getStFileSize(),
            info.getStFileType(),
            info.getNmOrder(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStExt1(),
            info.getStExt2()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(SelmAttach info) {
        String sql = "update SELM_ATTACH set ST_LINK_TABLE = ?, ST_LINK_ID = ?, ST_ATTACH_TYPE = ?, ST_FILENAME = ?, ST_FILE_SIZE = ?, ST_FILE_TYPE = ?, NM_ORDER = ?, DT_CREATE = ?, DT_UPDATE = ?, ST_EXT1 = ?, ST_EXT2 = ? where ST_ATTACH_ID = ?";
        Object[] obj = {
            info.getStLinkTable(),
            info.getStLinkId(),
            info.getStAttachType(),
            info.getStFilename(),
            info.getStFileSize(),
            info.getStFileType(),
            info.getNmOrder(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getStExt1(),
            info.getStExt2(),
            info.getStAttachId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update SELM_ATTACH set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from SELM_ATTACH";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stAttachId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stAttachId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stAttachId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId));
        delete(conds);
    }

    public PaginationArrayList<SelmAttach> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_ATTACH", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "SELM_ATTACH", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<SelmAttach> pal = new PaginationArrayList<SelmAttach>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            SelmAttach info = new SelmAttach();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<SelmAttach> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_ATTACH", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "SELM_ATTACH", "*", conds, suffix);
        }
        ArrayList<SelmAttach> al = new ArrayList<SelmAttach>();
        while (rs.next()) {
            SelmAttach info = new SelmAttach();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(SelmAttach info, RecordSet rs){
        info.setStAttachId(rs.getOriginalString("ST_ATTACH_ID"));
        info.setStLinkTable(rs.getOriginalString("ST_LINK_TABLE"));
        info.setStLinkId(rs.getOriginalString("ST_LINK_ID"));
        info.setStAttachType(rs.getOriginalString("ST_ATTACH_TYPE"));
        info.setStFilename(rs.getOriginalString("ST_FILENAME"));
        info.setStFileSize(rs.getOriginalString("ST_FILE_SIZE"));
        info.setClContent(rs.getOriginalString("CL_CONTENT"));
        info.setStFileType(rs.getOriginalString("ST_FILE_TYPE"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setDtUpdate(rs.getTimestamp("DT_UPDATE"));
        info.setStExt1(rs.getOriginalString("ST_EXT1"));
        info.setStExt2(rs.getOriginalString("ST_EXT2"));
    }

	public SelmAttach get(String stAttachId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId));
        List<SelmAttach> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

	
	
	public byte[] getAttachFildById(String stAttachId) {
		Conditions conds = Conditions.newAndConditions();
		conds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId));
		byte[] blContent = BlobHelper.getBlob("SELM_ATTACH", "BL_CONTENT",
				conds.toString(), conds.getObjectArray());

		return blContent;
	}

}
