//依赖jQuery
var dataEvent = [{
	"itemName": "残疾人交通补贴申请",
	"itemCode": "531200037400001",
	"piwikName": "上海市残疾人交通补贴申请"
}, {
	"itemName": "听力、言语残疾人信息卡套餐服务申请",
	"itemCode": "531200106500001",
	"piwikName": "听力、言语残疾人信息卡套餐服务申请"
}, {
	"itemName": "盲人有声读物阅览室（角）信息查询",
	"itemCode": "",
	"piwikName": "盲人有声读物阅览室（角）信息查询"
}, {
	"itemName": "无障碍电影放映点信息查询",
	"itemCode": "",
	"piwikName": "无障碍电影放映点信息查询"
}, {
	"itemName": "兵役档案查询",
	"itemCode": "531200101600001",
	"piwikName": "兵役档案查询"
}, {
	"itemName": "承包地确权登记档案",
	"itemCode": "531200147100001",
	"piwikName": "承包地确权登记档案"
}, {
	"itemName": "独生子女证档案查询",
	"itemCode": "531200021500001",
	"piwikName": "独生子女证档案查询"
}, {
	"itemName": "工伤认定档案查询",
	"itemCode": "531200106200001",
	"piwikName": "工伤认定档案查询"
}, {
	"itemName": "婚姻登记档案查询",
	"itemCode": "531200037000001",
	"piwikName": "婚姻登记档案查询"
}, {
	"itemName": "农民建房审批档案查询",
	"itemCode": "531200025500001",
	"piwikName": "农民建房审批档案查询"
}, {
	"itemName": "人才引进审批档案查询",
	"itemCode": "531200107700001",
	"piwikName": "人才引进审批档案查询"
}, {
	"itemName": "三峡移民档案查询",
	"itemCode": "531200018100001",
	"piwikName": "三峡移民档案查询"
}, {
	"itemName": "涉外婚姻登记档案查询",
	"itemCode": "531200013600001",
	"piwikName": "涉外婚姻登记档案查询"
}, {
	"itemName": "市级人才引进审批档案查询",
	"itemCode": "531200025300001",
	"piwikName": "市级人才引进审批档案查询"
}, {
	"itemName": "市三八红旗手登记档案查询",
	"itemCode": "531200024400001",
	"piwikName": "市三八红旗手登记档案查询"
}, {
	"itemName": "复员退伍军人档案查询",
	"itemCode": "531200105200001",
	"piwikName": "复员退伍军人档案查询"
}, {
	"itemName": "学籍档案查询",
	"itemCode": "531200105500001",
	"piwikName": "学籍档案查询"
}, {
	"itemName": "再生育子女审批档案查询",
	"itemCode": "531200024500001",
	"piwikName": "再生育子女审批档案查询"
}, {
	"itemName": "知青返城档案查询",
	"itemCode": "531200032100001",
	"piwikName": "知青返城档案查询"
}, {
	"itemName": "知青上山下乡档案查询",
	"itemCode": "531200104600001",
	"piwikName": "知青上山下乡档案查询"
}, {
	"itemName": "知青子女入户档案查询",
	"itemCode": "531200104500001",
	"piwikName": "知青子女入户档案查询"
}, {
	"itemName": "专业技术干部的农村家属迁往城镇审批档案查询",
	"itemCode": "312090185000",
	"piwikName": "专业技术干部的农村家属迁往城镇审批档案查询"
}, {
	"itemName": "信用报告查询",
	"itemCode": "",
	"piwikName": "信用报告查询"
}, {
	"itemName": "副食品价格补贴发放银行卡维护",
	"itemCode": "531200031100001",
	"piwikName": "副食品价格补贴发放银行卡维护"
}, {
	"itemName": "出境入境记录",
	"itemCode": "",
	"piwikName": "出境入境记录"
}, {
	"itemName": "非上海生源高校毕业生落户查询",
	"itemCode": "",
	"piwikName": "非上海生源高校毕业生落户查询"
}, {
	"itemName": "户籍人户分离人员居住登记受理",
	"itemCode": "531200008300001",
	"piwikName": "户籍人户分离人员居住登记受理"
}, {
	"itemName": "户籍人户分离人员居住登记注销",
	"itemCode": "531200008600001",
	"piwikName": "户籍人户分离人员居住登记注销"
}, {
	"itemName": "机动车违法信息查询",
	"itemCode": "",
	"piwikName": "机动车违法信息查询"
}, {
	"itemName": "敬老卡申领",
	"itemCode": "531200043200001",
	"piwikName": "敬老卡申领"
}, {
	"itemName": "居住证签注",
	"itemCode": "531200019400001",
	"piwikName": "居住证签注"
}, {
	"itemName": "开具有无违法犯罪记录证明",
	"itemCode": "",
	"piwikName": "开具有无违法犯罪记录证明"
}, {
	"itemName": "属地派出所查询",
	"itemCode": "",
	"piwikName": "属地派出所查询"
}, {
	"itemName": "同日出生人数",
	"itemCode": "",
	"piwikName": "同日出生人数"
}, {
	"itemName": "新版社保卡开通",
	"itemCode": "531200017600001",
	"piwikName": "新版社保卡开通"
}, {
	"itemName": "新生儿重名查询",
	"itemCode": "",
	"piwikName": "新生儿重名查询"
}, {
	"itemName": "户籍证明开具",
	"itemCode": "",
	"piwikName": "户籍证明开具"
}, {
	"itemName": "驾驶证违法信息查询",
	"itemCode": "",
	"piwikName": "驾驶证违法信息查询"
}, {
	"itemName": "地质资料档案查询",
	"itemCode": "",
	"piwikName": "地质资料档案查询"
}, {
	"itemName": "不动产登记信息自助查询、打印",
	"itemCode": "",
	"piwikName": "不动产登记信息自助查询、打印"
}, {
	"itemName": "公交卡余额查询",
	"itemCode": "",
	"piwikName": "公交卡余额查询"
}, {
	"itemName": "驾照考点查询",
	"itemCode": "",
	"piwikName": "驾照考点查询"
}, {
	"itemName": "交通卡服务网点查询",
	"itemCode": "",
	"piwikName": "交通卡服务网点查询"
}, {
	"itemName": "民办教育机构查询",
	"itemCode": "",
	"piwikName": "民办教育机构查询"
}, {
	"itemName": "全市示范高中信息查询",
	"itemCode": "",
	"piwikName": "全市示范高中信息查询"
}, {
	"itemName": "上海市学生事务中心存档证明",
	"itemCode": "",
	"piwikName": "上海市学生事务中心存档证明"
}, {
	"itemName": "上海市计算机等级考试成绩查询",
	"itemCode": "",
	"piwikName": "上海市计算机等级考试成绩查询"
}, {
	"itemName": "中外合作办学信息查询",
	"itemCode": "",
	"piwikName": "中外合作办学信息查询"
}, {
	"itemName": "幼升小报名信息查询(公办、民办)",
	"itemCode": "",
	"piwikName": "幼升小报名信息查询(公办、民办)"
}, {
	"itemName": "小升初报名信息查询(公办、民办)",
	"itemCode": "",
	"piwikName": "小升初报名信息查询(公办、民办)"
}, {
	"itemName": "3岁以下幼儿托育服务机构查询",
	"itemCode": "",
	"piwikName": "3岁以下幼儿托育服务机构查询"
}, {
	"itemName": "民办非学历培训机构查询",
	"itemCode": "",
	"piwikName": "民办非学历培训机构查询"
}, {
	"itemName": "市民网上实名认证服务",
	"itemCode": "531200025000001",
	"piwikName": "市民网上实名认证服务"
},{
	"itemName": "婚姻登记预约",
	"itemCode": "",
	"piwikName": "婚姻登记预约"
}, {
	"itemName": "城乡居民最低生活保障家庭证明出具",
	"itemCode": "531200037900001",
	"piwikName": "上海市城乡居民最低生活保障家庭证明出具"
}, {
	"itemName": "低收入困难家庭证明出具",
	"itemCode": "531200037900001",
	"piwikName": "上海市低收入困难家庭证明出具"
}, {
	"itemName": "定期定量生活补贴人员证明出具",
	"itemCode": "531200037900001",
	"piwikName": "上海市定期定量生活补贴人员证明出具"
}, {
	"itemName": "特困人员证明出具",
	"itemCode": "531200037900001",
	"piwikName": "上海市特困人员证明出具"
}, {
	"itemName": "因病支出型贫困家庭证明出具",
	"itemCode": "531200037900001",
	"piwikName": "上海市因病支出型贫困家庭证明出具"
}, {
	"itemName": "社区事务受理中心查询",
	"itemCode": "",
	"piwikName": "社区事务受理中心查询"
}, {
	"itemName": "宠物诊疗机构查询",
	"itemCode": "",
	"piwikName": "宠物诊疗机构查询"
}, {
	"itemName": "城乡居保缴费情况",
	"itemCode": "531200029600001",
	"piwikName": "城乡居民基本养老保险-城乡居保缴费情况"
}, {
	"itemName": "上年度养老保险个人权益记录单(城乡居保)",
	"itemCode": "312090078000",
	"piwikName": "城乡居民基本养老保险-上年度养老保险个人权益记录单"
}, {
	"itemName": "享受城乡居保养老金情况",
	"itemCode": "312090078000",
	"piwikName": "城乡居民基本养老保险-享受城乡居保养老金情况"
}, {
	"itemName": "业务审核办结情况",
	"itemCode": "312090078000",
	"piwikName": "城乡居民基本养老保险-业务审核办结情况"
}, {
	"itemName": "参加个人城镇基本养老保险缴费情况",
	"itemCode": "312090078000",
	"piwikName": "城镇职工基本养老保险-参加个人城镇基本养老保险缴费情况"
}, {
	"itemName": "个人享受城镇基本养老金情况",
	"itemCode": "312090078000",
	"piwikName": "城镇职工基本养老保险-个人享受城镇基本养老金情况"
}, {
	"itemName": "灵活就业人员电子对账单",
	"itemCode": "312090078000",
	"piwikName": "城镇职工基本养老保险-灵活就业人员电子对账单"
}, {
	"itemName": "上年度养老保险个人权益记录单",
	"itemCode": "312090078000",
	"piwikName": "城镇职工基本养老保险-上年度养老保险个人权益记录单"
}, {
	"itemName": "转往外省市缴费凭证",
	"itemCode": "312090078000",
	"piwikName": "城镇职工基本养老保险-转往外省市缴费凭证"
}, {
	"itemName": "居住证积分查询",
	"itemCode": "",
	"piwikName": "居住证积分查询"
}, {
	"itemName": "社保卡个人信息查询",
	"itemCode": "",
	"piwikName": "社保卡个人信息查询"
}, {
	"itemName": "养老金卡（折）调整",
	"itemCode": "531200049700001",
	"piwikName": "养老金卡（折）调整"
}, {
	"itemName": "失业保险金申领",
	"itemCode": "531050021200102",
	"piwikName": "失业保险金申领"
}, {
	"itemName": "失业登记",
	"itemCode": "531200061700001",
	"piwikName": "失业登记"
}, {
	"itemName": "劳动者基本信息查询及维护",
	"itemCode": "531200038400001",
	"piwikName": "劳动者基本信息查询及维护"
}, {
	"itemName": "本市户籍人员退出灵活就业登记",
	"itemCode": "531200020200001",
	"piwikName": "灵活就业登记"
}, {
	"itemName": "来沪人员灵活就业登记录入",
	"itemCode": "531200020200001",
	"piwikName": "灵活就业登记"
}, {
	"itemName": "本市户籍人员灵活就业登记",
	"itemCode": "531200020200001",
	"piwikName": "灵活就业登记"
}, {
	"itemName": "来沪人员灵活就业登记中止",
	"itemCode": "531200020200001",
	"piwikName": "灵活就业登记"
}, {
	"itemName": "申请大龄失业就业岗位补贴",
	"itemCode": "531200053700001",
	"piwikName": "申请大龄失业就业岗位补贴"
}, {
	"itemName": "申请“就业困难人员”灵活就业社会保险费补贴",
	"itemCode": "531200024700001",
	"piwikName": "申请“就业困难人员”灵活就业社会保险费补贴"
}, {
	"itemName": "餐饮脸谱",
	"itemCode": "",
	"piwikName": "餐饮脸谱"
}, {
	"itemName": "社会公用计量标准查询",
	"itemCode": "",
	"piwikName": "社会公用计量标准查询"
}, {
	"itemName": "法定计量检定机构考评员查询",
	"itemCode": "",
	"piwikName": "法定计量检定机构考评员查询"
}, {
	"itemName": "计量标准考评员查询",
	"itemCode": "",
	"piwikName": "计量标准考评员查询"
}, {
	"itemName": "二级注册计量师查询",
	"itemCode": "",
	"piwikName": "二级注册计量师查询"
}, {
	"itemName": "企业名称状态查询",
	"itemCode": "",
	"piwikName": "企业名称状态查询"
}, {
	"itemName": "合同示范文本查询",
	"itemCode": "",
	"piwikName": "合同示范文本查询"
}, {
	"itemName": "广告发布登记查询",
	"itemCode": "",
	"piwikName": "广告发布登记查询"
}, {
	"itemName": "律师兼职执业变更专职执业",
	"itemCode": "310100284000-06",
	"piwikName": "律师兼职执业变更专职执业"
}, {
	"itemName": "律师执业机构变更",
	"itemCode": "310100284000-02",
	"piwikName": "律师执业机构变更"
}, {
	"itemName": "律师执业证注销",
	"itemCode": "310100284000-04",
	"piwikName": "律师执业证注销"
}, {
	"itemName": "律师专职执业变更兼职执业",
	"itemCode": "310100284000-05",
	"piwikName": "律师专职执业变更兼职执业"
}, {
	"itemName": "首次申请律师兼职执业审核",
	"itemCode": "310100284000-03",
	"piwikName": "首次申请律师兼职执业审核"
}, {
	"itemName": "首次申请律师专职执业审核",
	"itemCode": "310100284000-01",
	"piwikName": "首次申请律师专职执业审核"
}, {
	"itemName": "重新申请律师兼职执业审核",
	"itemCode": "310100284000-07",
	"piwikName": "重新申请律师兼职执业审核"
}, {
	"itemName": "重新申请律师专职执业审核",
	"itemCode": "310100284000-08",
	"piwikName": "重新申请律师专职执业审核"
}, {
	"itemName": "办理结算服务项目的相关手续",
	"itemCode": "531200033100001",
	"piwikName": "办理结算服务项目的相关手续"
}, {
	"itemName": "办理就医记录册的申领、更换、补发",
	"itemCode": "531200037700001",
	"piwikName": "办理就医记录册的申领、更换、补发"
}, {
	"itemName": "办理居民医保受理登记",
	"itemCode": "531200036100001",
	"piwikName": "办理居民医保受理登记"
}, {
	"itemName": "办理医保网站密码申请及变更",
	"itemCode": "531200034900001",
	"piwikName": "办理医保网站密码申请及变更"
}, {
	"itemName": "办理医疗卡书面挂失及撤销",
	"itemCode": "531200032700001",
	"piwikName": "办理医疗卡书面挂失及撤销"
}, {
	"itemName": "本市开展异地就医的医院查询",
	"itemCode": "",
	"piwikName": "本市开展异地就医的医院查询"
}, {
	"itemName": "商业保险机构网点信息查询",
	"itemCode": "",
	"piwikName": "商业保险机构网点信息查询"
}, {
	"itemName": "医保及相关服务机构查询",
	"itemCode": "",
	"piwikName": "服务机构查询-医保及相关服务机构查询"
}, {
	"itemName": "医保诊疗项目约定服务医院查询",
	"itemCode": "",
	"piwikName": "服务机构查询-医保诊疗项目约定服务医院查询"
}, {
	"itemName": "长护险护理机构查询",
	"itemCode": "",
	"piwikName": "长护险护理机构查询"
}, {
	"itemName": "长护险评估机构查询",
	"itemCode": "",
	"piwikName": "长护险评估机构查询"
}, {
	"itemName": "参保人员待遇查询",
	"itemCode": "",
	"piwikName": "人员信息查询-参保人员待遇查询"
}, {
	"itemName": "年度累计医疗费用信息查询",
	"itemCode": "",
	"piwikName": "人员信息查询-年度累计医疗费用信息查询"
}, {
	"itemName": "医保就医明细查询",
	"itemCode": "",
	"piwikName": "人员信息查询-医保就医明细查询"
}, {
	"itemName": "帐户清算信息查询",
	"itemCode": "531200024600001",
	"piwikName": "人员信息查询-帐户清算信息查询"
}, {
	"itemName": "床位费医保支付标准",
	"itemCode": "",
	"piwikName": "药品及床位费支付标准查询"
}, {
	"itemName": "医保范围药品查询",
	"itemCode": "",
	"piwikName": "药品及床位费支付标准查询"
}, {
	"itemName": "医保个人信息查询",
	"itemCode": "531200023700001",
	"piwikName": "医保个人信息查询"
}, {
	"itemName": "医疗费用分担模拟计算器",
	"itemCode": "",
	"piwikName": "医疗费用分担模拟计算器"
}, {
	"itemName": "医疗机构查询",
	"itemCode": "",
	"piwikName": "医疗机构查询"
}, {
	"itemName": "异地就医一件事",
	"itemCode": "31LB00004000",
	"piwikName": "异地就医一件事（办理就医关系转移+跨省异地就医登记备案相关手续）"
}, {
	"itemName": "医保综合减负试算",
	"itemCode": "",
	"piwikName": "综合减负试算"
},{
	"itemName": "零星报销进度查询",
	"itemCode": "",
	"piwikName": "零星报销进度查询"
},{
	"itemName": "帮困补助进度查询",
	"itemCode": "",
	"piwikName": "帮困补助进度查询"
},{
	"itemName": "帮困登记缴费进度查询",
	"itemCode": "",
	"piwikName": "帮困登记缴费进度查询"
}, {
	"itemName": "纯公积金贷款受理网点查询",
	"itemCode": "",
	"piwikName": "纯公积金贷款受理网点查询"
}, {
	"itemName": "个人住房公积金信息查询",
	"itemCode": "531200022500001",
	"piwikName": "个人住房公积金信息查询"
}, {
	"itemName": "公积金贷款试算",
	"itemCode": "",
	"piwikName": "公积金贷款试算"
}, {
	"itemName": "公积金还款计算",
	"itemCode": "",
	"piwikName": "公积金还款计算"
}, {
	"itemName": "公积金缴存表查询",
	"itemCode": "",
	"piwikName": "公积金缴存表查询"
}, {
	"itemName": "公积金缴存计算",
	"itemCode": "",
	"piwikName": "公积金缴存计算"
}, {
	"itemName": "公积金缴存提取经办银行查询",
	"itemCode": "",
	"piwikName": "公积金缴存提取经办银行查询"
}, {
	"itemName": "公积金区管理部查询",
	"itemCode": "",
	"piwikName": "公积金区管理部查询"
}, {
	"itemName": "组合贷款各受理银行查询",
	"itemCode": "",
	"piwikName": "组合贷款各受理银行查询"
}, {
	"itemName": "物业企业信息查询",
	"itemCode": "",
	"piwikName": "物业企业信息查询"
}, {
	"itemName": "小区信息查询",
	"itemCode": "",
	"piwikName": "小区信息查询"
}, {
	"itemName": "上海市禁止、限制和控制危险化学品目录（第三批）查询",
	"itemCode": "",
	"piwikName": "上海市禁止、限制和控制危险化学品目录（第三批）查询"
}, {
	"itemName": "危险化学品生产企业安全生产许可证查询",
	"itemCode": "",
	"piwikName": "危险化学品生产企业安全生产许可证查询"
}, {
	"itemName": "危险化学品经营许可证核发查询",
	"itemCode": "",
	"piwikName": "危险化学品经营许可证核发查询"
}, {
	"itemName": "危险化学品建设项目信息查询",
	"itemCode": "",
	"piwikName": "危险化学品建设项目信息查询"
}, {
	"itemName": "安全评价机构资质许可查询",
	"itemCode": "",
	"piwikName": "安全评价机构资质许可查询"
}, {
	"itemName": "安全生产检测检验机构资质认可查询",
	"itemCode": "",
	"piwikName": "安全生产检测检验机构资质认可查询"
}, {
	"itemName": "安全生产协会会员培训机构条件核实情况查询",
	"itemCode": "",
	"piwikName": "安全生产协会会员培训机构条件核实情况查询"
}, {
	"itemName": "价格公示",
	"itemCode": "",
	"piwikName": "价格公示"
}, {
	"itemName": "耗材查询",
	"itemCode": "",
	"piwikName": "耗材查询"
}, {
	"itemName": "医师执业资格信息查询",
	"itemCode": "",
	"piwikName": "医师执业资格信息查询"
}, {
	"itemName": "护士执业资格信息查询",
	"itemCode": "",
	"piwikName": "护士执业资格信息查询"
}, {
	"itemName": "本市核酸检测采样机构查询",
	"itemCode": "",
	"piwikName": "本市核酸检测采样机构查询"
}, {
	"itemName": "预付卡信息查询",
	"itemCode": "",
	"piwikName": "预付卡信息查询"
}, {
	"itemName": "预付卡余额查询",
	"itemCode": "",
	"piwikName": "预付卡余额查询"
}, {
	"itemName": "预付卡警示名单查询",
	"itemCode": "",
	"piwikName": "预付卡警示名单查询"
}, {
	"itemName": "房产税查询",
	"itemCode": "",
	"piwikName": "房产税查询"
}];
var returnCord = function(dataList, name) {
	if(Array.isArray(dataList)) {
		for(var i = 0; i < dataList.length; i++) {
			if(dataList[i].itemName == name) {
				return dataList[i];
			}
		}
		return {
			"itemName": name,
			"itemCode": "",
			"piwikName": name
		}
	}
};
var logSheetAdd = function(n) {
	setTimeout(function() {
		var pageText = $(".headName").text();
		if(n != undefined) {
			pageText = n;
		}
		console.log(pageText);
		var codeval = returnCord(dataEvent, pageText).itemCode;
		var piwikName = returnCord(dataEvent, pageText).piwikName;
		console.log(codeval);
//		if(codeval == undefined) {
//			return;
//		};
		trackEvent(piwikName, codeval);
	}, 1000);
};
logSheetAdd();