package com.wondersgroup.selfapi.dao;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.wondersgroup.selfapi.bean.NetReservationDatedTemp;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;


/**
 * 预约过期临时表
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class NetReservationDatedTempDao {

    private Connection con = null;

    public NetReservationDatedTempDao() {
    }

    public NetReservationDatedTempDao(Connection con) {
        this.con = con;
    }

    public void add(NetReservationDatedTemp info) {
        String sql = "insert into NET_RESERVATION_DATED_TEMP(ST_TEMP_ID, ST_USER_ID, ST_USER_NAME, ST_MOBILE, NM_IDENTITY_TYPE, ST_IDENTITY_NO, ST_UNIT, ST_UNIFIED, DT_CREATE, DT_UPDATE, NM_COUNT, ST_EXT1, ST_EXT2) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStTempId(),
            info.getStUserId(),
            info.getStUserName(),
            info.getStMobile(),
            info.getNmIdentityType(),
            info.getStIdentityNo(),
            info.getStUnit(),
            info.getStUnified(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getNmCount(),
            info.getStExt1(),
            info.getStExt2()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(NetReservationDatedTemp info) {
        String sql = "update NET_RESERVATION_DATED_TEMP set ST_USER_ID = ?, ST_USER_NAME = ?, ST_MOBILE = ?, NM_IDENTITY_TYPE = ?, ST_IDENTITY_NO = ?, ST_UNIT = ?, ST_UNIFIED = ?, DT_CREATE = ?, DT_UPDATE = ?, NM_COUNT = ?, ST_EXT1 = ?, ST_EXT2 = ? where ST_TEMP_ID = ?";
        Object[] obj = {
            info.getStUserId(),
            info.getStUserName(),
            info.getStMobile(),
            info.getNmIdentityType(),
            info.getStIdentityNo(),
            info.getStUnit(),
            info.getStUnified(),
            info.getDtCreate(),
            info.getDtUpdate(),
            info.getNmCount(),
            info.getStExt1(),
            info.getStExt2(),
            info.getStTempId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update NET_RESERVATION_DATED_TEMP set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from NET_RESERVATION_DATED_TEMP";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stTempId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stTempId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_TEMP_ID", Condition.OT_EQUAL, stTempId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stTempId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_TEMP_ID", Condition.OT_EQUAL, stTempId));
        delete(conds);
    }

    public PaginationArrayList<NetReservationDatedTemp> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("NET_RESERVATION_DATED_TEMP", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "NET_RESERVATION_DATED_TEMP", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<NetReservationDatedTemp> pal = new PaginationArrayList<NetReservationDatedTemp>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            NetReservationDatedTemp info = new NetReservationDatedTemp();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<NetReservationDatedTemp> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("NET_RESERVATION_DATED_TEMP", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "NET_RESERVATION_DATED_TEMP", "*", conds, suffix);
        }
        ArrayList<NetReservationDatedTemp> al = new ArrayList<NetReservationDatedTemp>();
        while (rs.next()) {
            NetReservationDatedTemp info = new NetReservationDatedTemp();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(NetReservationDatedTemp info, RecordSet rs){
        info.setStTempId(rs.getOriginalString("ST_TEMP_ID"));
        info.setStUserId(rs.getOriginalString("ST_USER_ID"));
        info.setStUserName(rs.getOriginalString("ST_USER_NAME"));
        info.setStMobile(rs.getOriginalString("ST_MOBILE"));
        info.setNmIdentityType(rs.getBigDecimal("NM_IDENTITY_TYPE"));
        info.setStIdentityNo(rs.getOriginalString("ST_IDENTITY_NO"));
        info.setStUnit(rs.getOriginalString("ST_UNIT"));
        info.setStUnified(rs.getOriginalString("ST_UNIFIED"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setDtUpdate(rs.getTimestamp("DT_UPDATE"));
        info.setNmCount(rs.getBigDecimal("NM_COUNT"));
        info.setStExt1(rs.getOriginalString("ST_EXT1"));
        info.setStExt2(rs.getOriginalString("ST_EXT2"));
    }

	public NetReservationDatedTemp get(String stTempId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_TEMP_ID", Condition.OT_EQUAL, stTempId));
        List<NetReservationDatedTemp> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
