package com.wondersgroup.wdf.dao;

import org.springframework.stereotype.Repository;
import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 电子材料关联附件
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class UacAttachLinkDao {

    private Connection con = null;

    public UacAttachLinkDao() {
    }

    public UacAttachLinkDao(Connection con) {
        this.con = con;
    }

    public void add(UacAttachLink info) {
        String sql = "insert into UAC_ATTACH_LINK(ST_ESTUFF_ID, ST_ATTACH_ID, NM_ORDER, ST_FILENAME) values (?, ?, ?, ?)";
        Object[] obj = {
            info.getStEstuffId(),
            info.getStAttachId(),
            info.getNmOrder(),
            info.getStFileName()
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(UacAttachLink info) {
        String sql = "update UAC_ATTACH_LINK set NM_ORDER = ? where ST_ESTUFF_ID = ? and ST_ATTACH_ID = ?";
        Object[] obj = {
            info.getNmOrder(),
            info.getStEstuffId(),
            info.getStAttachId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update UAC_ATTACH_LINK set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from UAC_ATTACH_LINK";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stEstuffId, String[] stAttachId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stEstuffId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_ESTUFF_ID", Condition.OT_EQUAL, stEstuffId[i]));
            subconds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stEstuffId, String stAttachId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ESTUFF_ID", Condition.OT_EQUAL, stEstuffId));
        conds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId));
        delete(conds);
    }

    public PaginationArrayList<UacAttachLink> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_ATTACH_LINK", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "UAC_ATTACH_LINK", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<UacAttachLink> pal = new PaginationArrayList<UacAttachLink>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            UacAttachLink info = new UacAttachLink();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<UacAttachLink> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_ATTACH_LINK", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "UAC_ATTACH_LINK", "*", conds, suffix);
        }
        ArrayList<UacAttachLink> al = new ArrayList<UacAttachLink>();
        while (rs.next()) {
            UacAttachLink info = new UacAttachLink();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(UacAttachLink info, RecordSet rs){
        info.setStEstuffId(rs.getOriginalString("ST_ESTUFF_ID"));
        info.setStAttachId(rs.getOriginalString("ST_ATTACH_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setStFileName(rs.getOriginalString("ST_FILENAME"));
    }

	public UacAttachLink get(String stEstuffId, String stAttachId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ESTUFF_ID", Condition.OT_EQUAL, stEstuffId));
        conds.add(new Condition("ST_ATTACH_ID", Condition.OT_EQUAL, stAttachId));
        List<UacAttachLink> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

    public UacAttachLink getAth(String stEstuffId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ESTUFF_ID", Condition.OT_EQUAL, stEstuffId));
        List<UacAttachLink> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
