package com.wondersgroup.wdf.dao;

import java.math.*;
import java.sql.*;
import java.util.*;
import wfc.facility.tool.autocode.*;
import wfc.service.database.*;
import org.springframework.stereotype.Repository;

/**
 * 组关联事项
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class UacItemGroupLinkTwoDao {

    private Connection con = null;

    public UacItemGroupLinkTwoDao() {
    }

    public UacItemGroupLinkTwoDao(Connection con) {
        this.con = con;
    }

    public void add(UacItemGroupLinkTwo info) {
        String sql = "insert into UAC_ITEM_GROUP_LINK(ST_ITEM_ID, ST_GROUP_ID, NM_ORDER) values (?, ?, ?)";
        Object[] obj = {
            info.getStItemId(),
            info.getStGroupId(),
            info.getNmOrder()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(UacItemGroupLinkTwo info) {
        String sql = "update UAC_ITEM_GROUP_LINK set NM_ORDER = ? where ST_ITEM_ID = ? and ST_GROUP_ID = ?";
        Object[] obj = {
            info.getNmOrder(),
            info.getStItemId(),
            info.getStGroupId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update UAC_ITEM_GROUP_LINK set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from UAC_ITEM_GROUP_LINK";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stItemId, String[] stGroupId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stItemId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_ITEM_ID", Condition.OT_EQUAL, stItemId[i]));
            subconds.add(new Condition("ST_GROUP_ID", Condition.OT_EQUAL, stGroupId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stItemId, String stGroupId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ITEM_ID", Condition.OT_EQUAL, stItemId));
        conds.add(new Condition("ST_GROUP_ID", Condition.OT_EQUAL, stGroupId));
        delete(conds);
    }

    public PaginationArrayList<UacItemGroupLinkTwo> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_ITEM_GROUP_LINK", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "UAC_ITEM_GROUP_LINK", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<UacItemGroupLinkTwo> pal = new PaginationArrayList<UacItemGroupLinkTwo>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            UacItemGroupLinkTwo info = new UacItemGroupLinkTwo();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<UacItemGroupLinkTwo> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_ITEM_GROUP_LINK", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "UAC_ITEM_GROUP_LINK", "*", conds, suffix);
        }
        ArrayList<UacItemGroupLinkTwo> al = new ArrayList<UacItemGroupLinkTwo>();
        while (rs.next()) {
            UacItemGroupLinkTwo info = new UacItemGroupLinkTwo();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(UacItemGroupLinkTwo info, RecordSet rs){
        info.setStItemId(rs.getOriginalString("ST_ITEM_ID"));
        info.setStGroupId(rs.getOriginalString("ST_GROUP_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
    }

	public UacItemGroupLinkTwo get(String stItemId, String stGroupId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ITEM_ID", Condition.OT_EQUAL, stItemId));
        conds.add(new Condition("ST_GROUP_ID", Condition.OT_EQUAL, stGroupId));
        List<UacItemGroupLinkTwo> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
