package com.wondersgroup.wdf.dao;

import org.springframework.stereotype.Repository;
import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 办件关联物流
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class UacUapplyLsticsDao {

    private Connection con = null;

    public UacUapplyLsticsDao() {
    }

    public UacUapplyLsticsDao(Connection con) {
        this.con = con;
    }

    public void add(UacUapplyLstics info) {
        String sql = "insert into UAC_UAPPLY_LSTICS(ST_UNION_LOGISTICS_ID, ST_APPLY_ID, NM_ORDER, ST_NODE) values (?, ?, ?, ?)";
        Object[] obj = {
            info.getStUnionLogisticsId(),
            info.getStApplyId(),
            info.getNmOrder(),
            info.getStNode()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(UacUapplyLstics info) {
        String sql = "update UAC_UAPPLY_LSTICS set NM_ORDER = ?, ST_NODE = ? where ST_UNION_LOGISTICS_ID = ? and ST_APPLY_ID = ?";
        Object[] obj = {
            info.getNmOrder(),
            info.getStNode(),
            info.getStUnionLogisticsId(),
            info.getStApplyId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update UAC_UAPPLY_LSTICS set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from UAC_UAPPLY_LSTICS";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stUnionLogisticsId, String[] stApplyId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stUnionLogisticsId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_UNION_LOGISTICS_ID", Condition.OT_EQUAL, stUnionLogisticsId[i]));
            subconds.add(new Condition("ST_APPLY_ID", Condition.OT_EQUAL, stApplyId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stUnionLogisticsId, String stApplyId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_UNION_LOGISTICS_ID", Condition.OT_EQUAL, stUnionLogisticsId));
        conds.add(new Condition("ST_APPLY_ID", Condition.OT_EQUAL, stApplyId));
        delete(conds);
    }

    public PaginationArrayList<UacUapplyLstics> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_UAPPLY_LSTICS", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "UAC_UAPPLY_LSTICS", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<UacUapplyLstics> pal = new PaginationArrayList<UacUapplyLstics>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            UacUapplyLstics info = new UacUapplyLstics();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<UacUapplyLstics> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("UAC_UAPPLY_LSTICS", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "UAC_UAPPLY_LSTICS", "*", conds, suffix);
        }
        ArrayList<UacUapplyLstics> al = new ArrayList<UacUapplyLstics>();
        while (rs.next()) {
            UacUapplyLstics info = new UacUapplyLstics();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(UacUapplyLstics info, RecordSet rs){
        info.setStUnionLogisticsId(rs.getOriginalString("ST_UNION_LOGISTICS_ID"));
        info.setStApplyId(rs.getOriginalString("ST_APPLY_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setStNode(rs.getOriginalString("ST_NODE"));
    }

	public UacUapplyLstics get(String stUnionLogisticsId, String stApplyId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_UNION_LOGISTICS_ID", Condition.OT_EQUAL, stUnionLogisticsId));
        conds.add(new Condition("ST_APPLY_ID", Condition.OT_EQUAL, stApplyId));
        List<UacUapplyLstics> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

    public UacUapplyLstics getByApplyId(String stApplyId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_APPLY_ID", Condition.OT_EQUAL, stApplyId));
        List<UacUapplyLstics> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }
}
