//字典项
//缴存地
var countyOrg = [{
	"province": "上海市",
	"orgName": "上海市公积金管理中心",
	"city": "市辖区"
},{
	"province": "安徽省",
	"orgName": "安徽省省直住房公积金管理分中心",
	"city": "合肥市"
},{
	"province": "安徽省",
	"orgName": "芜湖市住房公积金管理中心",
	"city": "芜湖市"
}, {
	"province": "安徽省",
	"orgName": "蚌埠市住房公积金管理中心",
	"city": "蚌埠市"
}, {
	"province": "安徽省",
	"orgName": "淮南市住房公积金管理中心",
	"city": "淮南市"
}, {
	"province": "安徽省",
	"orgName": "安庆市住房公积金管理中心",
	"city": "安庆市"
},{
	"province": "安徽省",
	"orgName": "滁州市住房公积金管理中心",
	"city": "滁州市"
},{
	"province": "安徽省",
	"orgName": "池州市住房公积金管理中心",
	"city": "池州市"
}, {
	"province": "安徽省",
	"orgName": "宣城市住房公积金管理中心",
	"city": "宣城市"
}, {
	"province": "江苏省",
	"orgName": "苏州市住房公积金管理中心",
	"city": "苏州市"
}, {
	"province": "江苏省",
	"orgName": "江苏省省级机关住房资金管理中心",
	"city": "南京市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "浙江省直单位住房公积金管理中心",
	"city": "杭州市"
}, {
	"province": "浙江省",
	"orgName": "衢州市住房公积金管理中心",
	"city": "衢州市"
}, {
	"province": "浙江省",
	"orgName": "宁波市住房公积金管理中心",
	"city": "宁波市"
}, {
	"province": "浙江省",
	"orgName": "杭州住房公积金管理中心",
	"city": "杭州市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心椒江分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心黄岩分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心路桥分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心临海分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心温岭分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心玉环分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心三门分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心仙居分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心天台分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心德清分中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心长兴分中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心安吉分中心",
	"city": "湖州市"
},{
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心婺城管理部",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心金东管理部",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心兰溪分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心东阳分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心永康分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心浦江分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心武义分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心磐安分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心嘉善分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心平湖分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心海盐分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心海宁分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心桐乡分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心柯桥分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心上虞分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心诸暨分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心嵊州分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心新昌分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "义乌市住房公积金管理中心",
	"city": "义乌市"
}, {
	"province": "浙江省",
	"orgName": "温州市住房公积金管理中心",
	"city": "温州市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心定海分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心普陀分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心岱山分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心嵊泗分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心龙泉分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心青田分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心云和分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心庆元分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心缙云分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心遂昌分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心松阳分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心景宁分中心",
	"city": "丽水市"
}, {
	"province": "安徽省",
	"orgName": "合肥市住房公积金管理中心",
	"city": "合肥市"
}, {
	"province": "安徽省",
	"orgName": "黄山市住房公积金管理中心",
	"city": "黄山市"
}, {
	"province": "安徽省",
	"orgName": "马鞍山市住房公积金管理中心",
	"city": "马鞍山市"
}, {
	"province": "安徽省",
	"orgName": "淮北市住房公积金管理中心",
	"city": "淮北市"
}, {
	"province": "安徽省",
	"orgName": "铜陵市住房公积金管理中心",
	"city": "铜陵市"
}, {
	"province": "安徽省",
	"orgName": "阜阳市住房公积金管理中心",
	"city": "阜阳市"
}, {
	"province": "安徽省",
	"orgName": "宿州市住房公积金管理中心",
	"city": "宿州市"
}, {
	"province": "江苏省",
	"orgName": "连云港市住房公积金管理中心",
	"city": "连云港市"
}, {
	"province": "安徽省",
	"orgName": "六安市住房公积金中心",
	"city": "六安市"
}, {
	"province": "安徽省",
	"orgName": "亳州市住房公积金管理中心",
	"city": "亳州市"
}, {
	"province": "安徽省",
	"orgName": "淮南市住房公积金管理中心矿业集团分中心",
	"city": "淮南市"
}, {
	"province": "安徽省",
	"orgName": "淮北矿业集团住房公积金管理分中心",
	"city": "淮北市"
}, {
	"province": "安徽省",
	"orgName": "淮北市住房公积金管理中心皖北煤电集团公司分中心",
	"city": "淮北市"
}, {
	"province": "江苏省",
	"orgName": "盐城市住房公积金管理中心",
	"city": "盐城市"
}, {
	"province": "安徽省",
	"orgName": "马鞍山市住房公积金管理中心马钢（集团）控股有限公司分中心",
	"city": "马鞍山市"
}, {
	"province": "江苏省",
	"orgName": "镇江市住房公积金管理中心",
	"city": "镇江市"
}, {
	"province": "江苏省",
	"orgName": "南通市住房公积金管理中心",
	"city": "南通市"
}, {
	"province": "江苏省",
	"orgName": "泰州市住房公积金管理中心",
	"city": "泰州市"
}, {
	"province": "江苏省",
	"orgName": "常州市住房公积金管理中心",
	"city": "常州市"
}, {
	"province": "江苏省",
	"orgName": "无锡市住房公积金管理中心",
	"city": "无锡市"
}, {
	"province": "江苏省",
	"orgName": "南京住房公积金管理中心",
	"city": "南京市"
}, {
	"province": "江苏省",
	"orgName": "徐州市住房公积金管理中心",
	"city": "徐州市"
}, {
	"province": "江苏省",
	"orgName": "扬州市住房公积金管理中心",
	"city": "扬州市"
}, {
	"province": "江苏省",
	"orgName": "淮安市住房公积金管理中心",
	"city": "淮安市"
}]

//贷款地
var countyOrgDK = [{
	"province": "上海市",
	"orgName": "上海市公积金管理中心",
	"city": "市辖区"
}, {
	"province": "江苏省",
	"orgName": "苏州市住房公积金管理中心",
	"city": "苏州市"
}, {
	"province": "浙江省",
	"orgName": "浙江省直单位住房公积金管理中心",
	"city": "杭州市"
}, {
	"province": "浙江省",
	"orgName": "衢州市住房公积金管理中心",
	"city": "衢州市"
}, {
	"province": "浙江省",
	"orgName": "宁波市住房公积金管理中心",
	"city": "宁波市"
}, {
	"province": "浙江省",
	"orgName": "杭州住房公积金管理中心",
	"city": "杭州市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心椒江分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心黄岩分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心路桥分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心临海分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心温岭分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心玉环分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心三门分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心仙居分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "台州市住房公积金管理中心天台分中心",
	"city": "台州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心德清分中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心长兴分中心",
	"city": "湖州市"
}, {
	"province": "浙江省",
	"orgName": "湖州市住房公积金管理中心安吉分中心",
	"city": "湖州市"
},{
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心婺城管理部",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心金东管理部",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心兰溪分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心东阳分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心永康分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心浦江分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心武义分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "金华市住房公积金管理中心磐安分中心",
	"city": "金华市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心嘉善分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心平湖分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心海盐分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心海宁分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "嘉兴市住房公积金管理中心桐乡分中心",
	"city": "嘉兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心柯桥分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心上虞分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心诸暨分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心嵊州分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "绍兴市住房公积金管理中心新昌分中心",
	"city": "绍兴市"
}, {
	"province": "浙江省",
	"orgName": "义乌市住房公积金管理中心",
	"city": "义乌市"
}, {
	"province": "浙江省",
	"orgName": "温州市住房公积金管理中心",
	"city": "温州市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心定海分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心普陀分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心岱山分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "舟山市住房公积金管理中心嵊泗分中心",
	"city": "舟山市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心龙泉分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心青田分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心云和分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心庆元分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心缙云分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心遂昌分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心松阳分中心",
	"city": "丽水市"
}, {
	"province": "浙江省",
	"orgName": "丽水市住房公积金管理中心景宁分中心",
	"city": "丽水市"
}, {
	"province": "安徽省",
	"orgName": "黄山市住房公积金管理中心",
	"city": "黄山市"
}, {
	"province": "安徽省",
	"orgName": "马鞍山市住房公积金管理中心",
	"city": "马鞍山市"
}, {
	"province": "安徽省",
	"orgName": "铜陵市住房公积金管理中心",
	"city": "铜陵市"
}, {
	"province": "安徽省",
	"orgName": "宿州市住房公积金管理中心",
	"city": "宿州市"
}, {
	"province": "江苏省",
	"orgName": "连云港市住房公积金管理中心",
	"city": "连云港市"
}, {
	"province": "安徽省",
	"orgName": "六安市住房公积金中心",
	"city": "六安市"
}, {
	"province": "江苏省",
	"orgName": "镇江市住房公积金管理中心",
	"city": "镇江市"
}, {
	"province": "江苏省",
	"orgName": "盐城市住房公积金管理中心",
	"city": "盐城市"
}, {
	"province": "江苏省",
	"orgName": "南通市住房公积金管理中心",
	"city": "南通市"
}, {
	"province": "江苏省",
	"orgName": "泰州市住房公积金管理中心",
	"city": "泰州市"
}, {
	"province": "江苏省",
	"orgName": "常州市住房公积金管理中心",
	"city": "常州市"
}, {
	"province": "江苏省",
	"orgName": "无锡市住房公积金管理中心",
	"city": "无锡市"
}, {
	"province": "江苏省",
	"orgName": "徐州市住房公积金管理中心",
	"city": "徐州市"
}, {
	"province": "江苏省",
	"orgName": "扬州市住房公积金管理中心",
	"city": "扬州市"
}, {
	"province": "江苏省",
	"orgName": "淮安市住房公积金管理中心",
	"city": "淮安市"
}]
