package com.wondersgroup.selmAssist.dao;

import java.math.*;
import java.sql.*;
import java.util.*;
import wfc.facility.tool.autocode.*;
import wfc.service.database.*;
import org.springframework.stereotype.Repository;

import com.wondersgroup.selmAssist.bean.SelmDeviceAssist;

/**
 * 设备关联人员
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class SelmDeviceAssistDao {

    private Connection con = null;

    public SelmDeviceAssistDao() {
    }

    public SelmDeviceAssistDao(Connection con) {
        this.con = con;
    }

    public void add(SelmDeviceAssist info) {
        String sql = "insert into SELM_DEVICE_ASSIST(ST_ASSIST_ID, ST_DEVICE_ID, NM_ORDER) values (?, ?, ?)";
        Object[] obj = {
            info.getStAssistId(),
            info.getStDeviceId(),
            info.getNmOrder()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(SelmDeviceAssist info) {
        String sql = "update SELM_DEVICE_ASSIST set NM_ORDER = ? where ST_ASSIST_ID = ? and ST_DEVICE_ID = ?";
        Object[] obj = {
            info.getNmOrder(),
            info.getStAssistId(),
            info.getStDeviceId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update SELM_DEVICE_ASSIST set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from SELM_DEVICE_ASSIST";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stAssistId, String[] stDeviceId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stAssistId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_ASSIST_ID", Condition.OT_EQUAL, stAssistId[i]));
            subconds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stAssistId, String stDeviceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ASSIST_ID", Condition.OT_EQUAL, stAssistId));
        conds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId));
        delete(conds);
    }

    public PaginationArrayList<SelmDeviceAssist> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_DEVICE_ASSIST", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "SELM_DEVICE_ASSIST", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<SelmDeviceAssist> pal = new PaginationArrayList<SelmDeviceAssist>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            SelmDeviceAssist info = new SelmDeviceAssist();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<SelmDeviceAssist> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_DEVICE_ASSIST", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "SELM_DEVICE_ASSIST", "*", conds, suffix);
        }
        ArrayList<SelmDeviceAssist> al = new ArrayList<SelmDeviceAssist>();
        while (rs.next()) {
            SelmDeviceAssist info = new SelmDeviceAssist();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(SelmDeviceAssist info, RecordSet rs){
        info.setStAssistId(rs.getOriginalString("ST_ASSIST_ID"));
        info.setStDeviceId(rs.getOriginalString("ST_DEVICE_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
    }

	public SelmDeviceAssist get(String stAssistId, String stDeviceId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_ASSIST_ID", Condition.OT_EQUAL, stAssistId));
        conds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId));
        List<SelmDeviceAssist> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

}
