package com.wondersgroup.app.dao;

import java.math.*;
import java.sql.*;
import java.util.*;

import wfc.facility.tool.autocode.*;
import wfc.service.database.*;
import org.springframework.stereotype.Repository;

import com.wondersgroup.app.bean.SelmDeviceItemType;

/**
 * 设备关联事项类别
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class SelmDeviceItemTypeDao {

    private Connection con = null;

    public SelmDeviceItemTypeDao() {
    }

    public SelmDeviceItemTypeDao(Connection con) {
        this.con = con;
    }

    public void add(SelmDeviceItemType info) {
        String sql = "insert into SELM_DEVICE_ITEMTYPE(ST_DEVICE_ID, ST_ITEM_TYPE_ID, NM_SORT) values (?, ?, ?)";
        Object[] obj = {
            info.getStDeviceId(),
            info.getStItemTypeId(),
            info.getNmSort()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(SelmDeviceItemType info) {
        String sql = "update SELM_DEVICE_ITEMTYPE set NM_SORT = ? where ST_DEVICE_ID = ? and ST_ITEM_TYPE_ID = ?";
        Object[] obj = {
            info.getNmSort(),
            info.getStDeviceId(),
            info.getStItemTypeId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update SELM_DEVICE_ITEMTYPE set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from SELM_DEVICE_ITEMTYPE";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }


	public void delete(String stDeviceId, String stItemTypeId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId));
        conds.add(new Condition("ST_ITEM_TYPE_ID", Condition.OT_EQUAL, stItemTypeId));
        delete(conds);
    }
	
	

    public PaginationArrayList<SelmDeviceItemType> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_DEVICE_ITEMTYPE", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "SELM_DEVICE_ITEMTYPE", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<SelmDeviceItemType> pal = new PaginationArrayList<SelmDeviceItemType>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
        	SelmDeviceItemType info = new SelmDeviceItemType();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<SelmDeviceItemType> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("SELM_DEVICE_ITEMTYPE", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "SELM_DEVICE_ITEMTYPE", "*", conds, suffix);
        }
        ArrayList<SelmDeviceItemType> al = new ArrayList<SelmDeviceItemType>();
        while (rs.next()) {
        	SelmDeviceItemType info = new SelmDeviceItemType();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(SelmDeviceItemType info, RecordSet rs){
        info.setStDeviceId(rs.getOriginalString("ST_DEVICE_ID"));
        info.setStItemTypeId(rs.getOriginalString("ST_ITEM_TYPE_ID"));
        info.setNmSort(rs.getBigDecimal("NM_SORT"));
    }

	public SelmDeviceItemType get(String stDeviceId, String stItemTypeId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DEVICE_ID", Condition.OT_EQUAL, stDeviceId));
        conds.add(new Condition("ST_ITEM_TYPE_ID", Condition.OT_EQUAL, stItemTypeId));
        List<SelmDeviceItemType> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

	
}
