package com.wondersgroup.statistics.dao;

import java.math.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;

import wfc.facility.tool.autocode.*;
import wfc.service.database.*;

import org.springframework.stereotype.Repository;

import com.wondersgroup.statistics.bean.AnalyticsVisitedDetail;
import com.wondersgroup.statistics.bean.SelmClientStatDay;
import com.wondersgroup.statistics.bean.SelmStatistics;
import com.wondersgroup.statistics.bean.SelmStatisticsDay;

/**
 * 网站统计详细
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class AnalyticsVisitedDetailDao {

    private Connection con = null;

    public AnalyticsVisitedDetailDao() {
    }

    public AnalyticsVisitedDetailDao(Connection con) {
        this.con = con;
    }

    public void add(AnalyticsVisitedDetail info) {
        String sql = "insert into ANALYTICS_VISITED_DETAIL(ST_DETAIL_ID, ST_APP, ST_IP, ST_DOMAIN, ST_URL, ST_TITLE, ST_SCREEN_W, ST_SCREEN_H, ST_REFERRER, ST_OS, ST_CLIENT, ST_LANGUAGE, ST_UA, ST_COOKIE, ST_NET_FLAG, ST_NET_SUB_FLAG, DT_VISITED, ST_EXT1, ST_EXT2) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStDetailId(),
            info.getStApp(),
            info.getStIp(),
            info.getStDomain(),
            info.getStUrl(),
            info.getStTitle(),
            info.getStScreenW(),
            info.getStScreenH(),
            info.getStReferrer(),
            info.getStOs(),
            info.getStClient(),
            info.getStLanguage(),
            info.getStUa(),
            info.getStCookie(),
            info.getStNetFlag(),
            info.getStNetSubFlag(),
            info.getDtVisited(),
            info.getStExt1(),
            info.getStExt2()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(AnalyticsVisitedDetail info) {
        String sql = "update ANALYTICS_VISITED_DETAIL set ST_APP = ?, ST_IP = ?, ST_DOMAIN = ?, ST_URL = ?, ST_TITLE = ?, ST_SCREEN_W = ?, ST_SCREEN_H = ?, ST_REFERRER = ?, ST_OS = ?, ST_CLIENT = ?, ST_LANGUAGE = ?, ST_UA = ?, ST_COOKIE = ?, ST_NET_FLAG = ?, ST_NET_SUB_FLAG = ?, DT_VISITED = ?, ST_EXT1 = ?, ST_EXT2 = ? where ST_DETAIL_ID = ?";
        Object[] obj = {
            info.getStApp(),
            info.getStIp(),
            info.getStDomain(),
            info.getStUrl(),
            info.getStTitle(),
            info.getStScreenW(),
            info.getStScreenH(),
            info.getStReferrer(),
            info.getStOs(),
            info.getStClient(),
            info.getStLanguage(),
            info.getStUa(),
            info.getStCookie(),
            info.getStNetFlag(),
            info.getStNetSubFlag(),
            info.getDtVisited(),
            info.getStExt1(),
            info.getStExt2(),
            info.getStDetailId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update ANALYTICS_VISITED_DETAIL set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from ANALYTICS_VISITED_DETAIL";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stDetailId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stDetailId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_DETAIL_ID", Condition.OT_EQUAL, stDetailId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stDetailId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DETAIL_ID", Condition.OT_EQUAL, stDetailId));
        delete(conds);
    }

    public PaginationArrayList<AnalyticsVisitedDetail> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("ANALYTICS_VISITED_DETAIL", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "ANALYTICS_VISITED_DETAIL", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<AnalyticsVisitedDetail> pal = new PaginationArrayList<AnalyticsVisitedDetail>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            AnalyticsVisitedDetail info = new AnalyticsVisitedDetail();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<AnalyticsVisitedDetail> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("ANALYTICS_VISITED_DETAIL", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "ANALYTICS_VISITED_DETAIL", "*", conds, suffix);
        }
        ArrayList<AnalyticsVisitedDetail> al = new ArrayList<AnalyticsVisitedDetail>();
        while (rs.next()) {
            AnalyticsVisitedDetail info = new AnalyticsVisitedDetail();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public List<AnalyticsVisitedDetail> queryStNetFlag(Conditions conds, String suffix) {
    	RecordSet rs;
    	if (con == null) {
    		rs = SQL.query("ANALYTICS_VISITED_DETAIL", "ST_NET_FLAG", conds, suffix);
    	} else {
    		rs = SQL.query(con, "ANALYTICS_VISITED_DETAIL", "ST_NET_FLAG", conds, suffix);
    	}
    	ArrayList<AnalyticsVisitedDetail> al = new ArrayList<AnalyticsVisitedDetail>();
    	while (rs.next()) {
    		AnalyticsVisitedDetail info = new AnalyticsVisitedDetail();
    		setProperties(info, rs);
    		al.add(info);
    	}
    	return al;
    }
   /* 
    // 查询业务统计数据(前一天的数据)
    public List<SelmStatistics> query(String data) {
    	String sql = "select ST_NET_FLAG, count(ST_NET_FLAG) AS count from ANALYTICS_VISITED_DETAIL where DT_VISITED =? GROUP BY ST_NET_FLAG";
    	Object[] obj = { data };
    	RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql);
        } else {
            rs = SQL.execute(con, sql);
        }
        ArrayList<SelmStatistics> al = new ArrayList<SelmStatistics>();
        while (rs.next()) {
        	SelmStatistics info = new SelmStatistics();
            info.setStNetFlag(rs.getOriginalString("ST_NET_FLAG"));
            info.setStName(rs.getOriginalString("ST_NET_FLAG"));
            info.setNmCount(rs.getBigDecimal("count"));
            al.add(info);
        }
        return al;
    }
    */
    
    // 查询业务统计数据
    public List<SelmStatistics> query() {
    	String sql = "select ST_NET_FLAG, count(ST_NET_FLAG) AS count from ANALYTICS_VISITED_DETAIL GROUP BY ST_NET_FLAG";
        RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql);
        } else {
            rs = SQL.execute(con, sql);
        }
        ArrayList<SelmStatistics> al = new ArrayList<SelmStatistics>();
        while (rs.next()) {
        	SelmStatistics info = new SelmStatistics();
            info.setStNetFlag(rs.getOriginalString("ST_NET_FLAG"));
            info.setStName(rs.getOriginalString("ST_NET_FLAG"));
            info.setNmCount(rs.getBigDecimal("count"));
            al.add(info);
        }
        return al;
    }
    
  
   // 查询业务统计（按天）数据
    public List<SelmStatisticsDay> count(SelmStatistics selmStatistics) {
    	String sql = "";
    	if(DB.getDatabaseName()=="MySQL"){
    		 sql = "select DATE_FORMAT(DT_VISITED,'%Y-%m-%d') days, count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? GROUP BY days";
    	}else{
    		sql = "select convert(char(10),DT_VISITED,102) as [day],count(convert(char(10),DT_VISITED,102)) cnt from analytics_visited_detail where ST_NET_FLAG = ? group by convert(char(10),DT_VISITED,102) order by [day]";
    	}
    	//
    	 Object[] obj = {selmStatistics.getStNetFlag()};
    	RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql, obj);
        } else {
            rs = SQL.execute(con, sql, obj);
        }
        ArrayList<SelmStatisticsDay> al = new ArrayList<SelmStatisticsDay>();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //String format = simpleDateFormat.format(new Date());
        while (rs.next()) {
        	SelmStatisticsDay info = new SelmStatisticsDay();
            info.setStStatisticsId(selmStatistics.getStNetFlag());
            String time = rs.getOriginalString("day");
            String[] split = time.split("\\.");
            String str = split[0] + "-" + split[1] + "-" +split[2];
            try {
				Date date = simpleDateFormat.parse(str);
				String stDate = simpleDateFormat.format(date);
		        //String stDate = simpleDateFormat.format(time);
		        info.setStDate(stDate + "");
			} catch (ParseException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
           
            info.setNmCount(rs.getBigDecimal("cnt"));
           /* String days = stDate + " 00:00:00";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			try {
				Date date = dateFormat.parse(days);
				String formatDate = dateFormat.format(date);
	            Timestamp ts = new Timestamp(System.currentTimeMillis());
	            ts = Timestamp.valueOf(formatDate);
	            info.setDtTime(ts);
			} catch (ParseException e) {
				e.printStackTrace();
			}*/
            info.setDtTime(new Timestamp(System
					.currentTimeMillis()));
            al.add(info);
        }
        return al;
    }
    
    
    
    
    
    // 查询业务统计（按天）数据(更新前一天)
    public List<SelmStatisticsDay> yesterdayCount(SelmStatistics selmStatistics,String date) {
    	String sql = "";
    	if(DB.getDatabaseName()=="MySQL"){
    		 sql = "select count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? and DT_VISITED LIKE ?";
    	}else{
    		sql = "select count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? and convert(varchar,DT_VISITED,121) LIKE ? ";
    	}
    	//
    	 Object[] obj = {
    			 selmStatistics.getStNetFlag(),
    			 date + "%"
    	 };
    	RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql, obj);
        } else {
            rs = SQL.execute(con, sql, obj);
        }
        ArrayList<SelmStatisticsDay> al = new ArrayList<SelmStatisticsDay>();
        while (rs.next()) {
        	SelmStatisticsDay info = new SelmStatisticsDay();
            info.setStStatisticsId(selmStatistics.getStStatisticsId());
            info.setStDate(date);
            info.setNmCount(rs.getBigDecimal("COUNT"));
            String days = date + " 00:00:00";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			try {
				Date time = dateFormat.parse(days);
				String formatDate = dateFormat.format(time);
	            Timestamp ts = new Timestamp(System.currentTimeMillis());
	            ts = Timestamp.valueOf(formatDate);
	            info.setDtTime(ts);
			} catch (ParseException e) {
				e.printStackTrace();
			}
            
            al.add(info);
        }
        return al;
    }
    
    
    
    
    //查询终端业务统计（按天）数据
    public List<SelmClientStatDay> clientCount(SelmStatistics selmStatistics, SelmStatisticsDay selmStatisticsDay) {
    	String sql = "";
    	if(DB.getDatabaseName()=="MySQL"){
    		sql = "select ST_COOKIE, count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? AND DT_VISITED LIKE ? GROUP BY ST_COOKIE";
    	}else{
    		sql = "select ST_COOKIE, count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? AND convert(varchar,DT_VISITED,121) LIKE ? GROUP BY ST_COOKIE";
    	}
    	//
    	 Object[] obj = {
    			 selmStatistics.getStNetFlag(),
    			 selmStatisticsDay.getStDate() + "%"
    	 };
    	RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql, obj);
        } else {
            rs = SQL.execute(con, sql, obj);
        }
        ArrayList<SelmClientStatDay> al = new ArrayList<SelmClientStatDay>();
        while (rs.next()) {
        	SelmClientStatDay info = new SelmClientStatDay();
            info.setStStatisticsId(selmStatisticsDay.getStStatisticsId());
            info.setStDate(selmStatisticsDay.getStDate());
            info.setStMachineId(rs.getOriginalString("ST_COOKIE"));
            info.setNmCount(rs.getBigDecimal("COUNT"));
            String days = selmStatisticsDay.getStDate() + " 00:00:00";
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			try {
				Date date = dateFormat.parse(days);
				String formatDate = dateFormat.format(date);
	            Timestamp ts = new Timestamp(System.currentTimeMillis());
	            ts = Timestamp.valueOf(formatDate);
	            info.setDtTime(ts);
			} catch (ParseException e) {
				e.printStackTrace();
			}
            
            al.add(info);
        }
        return al;
    }
    
    
    public List<SelmStatistics> statisticsEveryDay() {
    	String sql = "select ST_NET_FLAG, count(ST_NET_FLAG) AS count from ANALYTICS_VISITED_DETAIL GROUP BY ST_NET_FLAG";
        RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql);
        } else {
            rs = SQL.execute(con, sql);
        }
        ArrayList<SelmStatistics> al = new ArrayList<SelmStatistics>();
        while (rs.next()) {
        	SelmStatistics info = new SelmStatistics();
            info.setStNetFlag(rs.getOriginalString("ST_NET_FLAG"));
            info.setStName(rs.getOriginalString("ST_NET_FLAG"));
            info.setNmCount(rs.getBigDecimal("count"));
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(AnalyticsVisitedDetail info, RecordSet rs){
        info.setStDetailId(rs.getOriginalString("ST_DETAIL_ID"));
        info.setStApp(rs.getOriginalString("ST_APP"));
        info.setStIp(rs.getOriginalString("ST_IP"));
        info.setStDomain(rs.getOriginalString("ST_DOMAIN"));
        info.setStUrl(rs.getOriginalString("ST_URL"));
        info.setStTitle(rs.getOriginalString("ST_TITLE"));
        info.setStScreenW(rs.getOriginalString("ST_SCREEN_W"));
        info.setStScreenH(rs.getOriginalString("ST_SCREEN_H"));
        info.setStReferrer(rs.getOriginalString("ST_REFERRER"));
        info.setStOs(rs.getOriginalString("ST_OS"));
        info.setStClient(rs.getOriginalString("ST_CLIENT"));
        info.setStLanguage(rs.getOriginalString("ST_LANGUAGE"));
        info.setStUa(rs.getOriginalString("ST_UA"));
        info.setStCookie(rs.getOriginalString("ST_COOKIE"));
        info.setStNetFlag(rs.getOriginalString("ST_NET_FLAG"));
        info.setStNetSubFlag(rs.getOriginalString("ST_NET_SUB_FLAG"));
        info.setDtVisited(rs.getOriginalString("DT_VISITED"));
        info.setStExt1(rs.getOriginalString("ST_EXT1"));
        info.setStExt2(rs.getOriginalString("ST_EXT2"));
    }

	public AnalyticsVisitedDetail get(String stDetailId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_DETAIL_ID", Condition.OT_EQUAL, stDetailId));
        List<AnalyticsVisitedDetail> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }

	public SelmStatistics getCount(String stNetFlag) {
		SelmStatistics selmStatistics = new SelmStatistics();
		selmStatistics.setStNetFlag(stNetFlag);
        List<SelmStatistics> list = queryBystNetFlag(selmStatistics);
        return list.size() > 0 ? list.get(0) : null;
    }

	  public List<SelmStatistics> queryBystNetFlag(SelmStatistics selmStatistics) {
	    	String sql = "select count(ST_NET_FLAG) AS count from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? GROUP BY ST_NET_FLAG";
	    	Object[] obj = {
	    			selmStatistics.getStNetFlag()        	
	            };
	    	RecordSet rs;
	        if (con == null) {
	        	rs = SQL.execute(sql, obj);
	        } else {
	        	rs = SQL.execute(con, sql, obj);
	        }
	    	ArrayList<SelmStatistics> al = new ArrayList<SelmStatistics>();
	    	while (rs.next()) {
	    		SelmStatistics info = new SelmStatistics();
	    		info.setNmCount(rs.getBigDecimal("count"));
	    		al.add(info);
	    	}
	    	return al;
	    }
	  
	  
	  
	public int suCount(String stDeviceId) {
		String sql = "SELECT count(*) count from analytics_visited_detail where ST_COOKIE= ?";
		Object[] obj = { stDeviceId };
		RecordSet rs;
		if (con == null) {
			rs = SQL.execute(sql, obj);
		} else {
			rs = SQL.execute(con, sql, obj);
		}
		int cont = 0;
		while (rs.next()) {
			BigDecimal bigDecimal = rs.getBigDecimal("count");
			cont = bigDecimal.intValue();
		}
		return cont;
	}

	public List<SelmClientStatDay> yesterdayClientCount(
			SelmStatistics selmStatistics, SelmStatisticsDay selmStatisticsDay) {
		String sql = "select ST_COOKIE, count(ST_NET_FLAG) COUNT from ANALYTICS_VISITED_DETAIL where ST_NET_FLAG = ? AND DT_VISITED LIKE ? GROUP BY ST_COOKIE";
   	 Object[] obj = {
   			 selmStatistics.getStNetFlag(),
   			 selmStatisticsDay.getStDate() + "%"
   	 };
   	RecordSet rs;
       if (con == null) {
           rs = SQL.execute(sql, obj);
       } else {
           rs = SQL.execute(con, sql, obj);
       }
       ArrayList<SelmClientStatDay> al = new ArrayList<SelmClientStatDay>();
       while (rs.next()) {
       	   SelmClientStatDay info = new SelmClientStatDay();
           info.setStStatisticsId(selmStatistics.getStStatisticsId());
           info.setStDate(selmStatisticsDay.getStDate());
           info.setStMachineId(rs.getOriginalString("ST_COOKIE"));
           info.setNmCount(rs.getBigDecimal("COUNT"));
           String days = selmStatisticsDay.getStDate() + " 00:00:00";
           SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			try {
				Date date = dateFormat.parse(days);
				String formatDate = dateFormat.format(date);
	            Timestamp ts = new Timestamp(System.currentTimeMillis());
	            ts = Timestamp.valueOf(formatDate);
	            info.setDtTime(ts);
			} catch (ParseException e) {
				e.printStackTrace();
			}
           
           al.add(info);
       }
       return al;
	}

	public int getAnalyticsCount(String stItemName) {
		String sql = "SELECT COUNT(ST_DETAIL_ID) cont from ANALYTICS_VISITED_DETAIL WHERE ST_NET_FLAG =? ";
		Object[] obj = { stItemName };
		RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql,obj);
        } else {
            rs = SQL.execute(con, sql,obj);
        }
        int cont = 0;
		while (rs.next()) {
			BigDecimal bigDecimal = rs.getBigDecimal("cont");
			cont = bigDecimal.intValue();
		}
		return cont;
	
	}
	
	public int getAnalyticsCount(String stItemName,  String startDate, String endDate) {
		String sql = "SELECT COUNT(ST_DETAIL_ID) cont from ANALYTICS_VISITED_DETAIL WHERE ST_NET_FLAG =? and DT_VISITED >= ? and DT_VISITED <= ?";
		Object[] obj = { stItemName,Timestamp.valueOf(startDate),Timestamp.valueOf(endDate) };
		RecordSet rs;
        if (con == null) {
            rs = SQL.execute(sql,obj);
        } else {
            rs = SQL.execute(con, sql,obj);
        }
        int cont = 0;
		while (rs.next()) {
			BigDecimal bigDecimal = rs.getBigDecimal("cont");
			cont = bigDecimal.intValue();
		}
		return cont;
	
	}
}
