package com.wondersgroup.api.dao;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import wfc.facility.tool.autocode.PaginationArrayList;
import wfc.service.database.Condition;
import wfc.service.database.Conditions;
import wfc.service.database.RecordSet;
import wfc.service.database.SQL;

import com.wondersgroup.api.bean.ApidocModule;

/**
 * 模块
 * @author generated by wfc.facility.tool.autocode.InternalDaoGenerator
 */
@Repository
public class ApidocModuleDao {

    private Connection con = null;

    public ApidocModuleDao() {
    }

    public ApidocModuleDao(Connection con) {
        this.con = con;
    }

    public void add(ApidocModule info) {
        String sql = "insert into APIDOC_MODULE(ST_MODULE_ID, ST_MODULE_NAME, ST_REMARK, ST_PROJECT_ID, NM_ORDER, ST_PARENT_ID, DT_CREATE, ST_EXT1, ST_EXT2) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Object[] obj = {
            info.getStModuleId(),
            info.getStModuleName(),
            info.getStRemark(),
            info.getStProjectId(),
            info.getNmOrder(),
            info.getStParentId(),
            info.getDtCreate(),
            info.getStExt1(),
            info.getStExt2()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public void update(ApidocModule info) {
        String sql = "update APIDOC_MODULE set ST_MODULE_NAME = ?, ST_REMARK = ?, ST_PROJECT_ID = ?, NM_ORDER = ?, ST_PARENT_ID = ?, DT_CREATE = ?, ST_EXT1 = ?, ST_EXT2 = ? where ST_MODULE_ID = ?";
        Object[] obj = {
            info.getStModuleName(),
            info.getStRemark(),
            info.getStProjectId(),
            info.getNmOrder(),
            info.getStParentId(),
            info.getDtCreate(),
            info.getStExt1(),
            info.getStExt2(),
            info.getStModuleId()        	
        };
        if (con == null) {
            SQL.execute(sql, obj);
        } else {
            SQL.execute(con, sql, obj);
        }
    }

    public int update(Map<String, Object> map, Conditions conds) {
        String sql = "update APIDOC_MODULE set ";
        List<Object> list = new ArrayList<Object>();
        int i = 0;
        for (String field : map.keySet()) {
            if (i++ > 0) {
                sql += ", ";
            }
            sql += field + " = ?";
            list.add(map.get(field));
        }
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            list.addAll(conds.getObjectList());
            if (con == null) {
                return SQL.execute(sql, list.toArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, list.toArray()).TOTAL_RECORD_COUNT;
            }
        }
    }
    
    public int delete(Conditions conds) {
        String sql = "delete from APIDOC_MODULE";
        String subsql = conds != null ? conds.toString() : "";
        if ("".equals(subsql)) {
            if (con == null) {
                return SQL.execute(sql).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql).TOTAL_RECORD_COUNT;
            }
        } else {
            sql += " where " + subsql;
            if (con == null) {
                return SQL.execute(sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            } else {
                return SQL.execute(con, sql, conds.getObjectArray()).TOTAL_RECORD_COUNT;
            }
        }
    }

	public void delete(String[] stModuleId) {
        Conditions conds = Conditions.newOrConditions();
        for (int i = 0; i < stModuleId.length; i++) {
            Conditions subconds = Conditions.newAndConditions();
            subconds.add(new Condition("ST_MODULE_ID", Condition.OT_EQUAL, stModuleId[i]));
            conds.add(subconds);
        }
        delete(conds);
    }

	public void delete(String stModuleId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_MODULE_ID", Condition.OT_EQUAL, stModuleId));
        delete(conds);
    }

    public PaginationArrayList<ApidocModule> query(Conditions conds, String suffix, int pageSize, int currentPage) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("APIDOC_MODULE", "*", conds, suffix, pageSize, currentPage);
        } else {
            rs = SQL.query(con, "APIDOC_MODULE", "*", conds, suffix, pageSize, currentPage);
        }
        PaginationArrayList<ApidocModule> pal = new PaginationArrayList<ApidocModule>(rs.TOTAL_RECORD_COUNT, rs.COMMON_PAGE_SIZE, rs.CURRENT_PAGE);
        while (rs.next()) {
            ApidocModule info = new ApidocModule();
            setProperties(info, rs);
            pal.add(info);
        }
        return pal;
    }

    public List<ApidocModule> query(Conditions conds, String suffix) {
        RecordSet rs;
        if (con == null) {
            rs = SQL.query("APIDOC_MODULE", "*", conds, suffix);
        } else {
            rs = SQL.query(con, "APIDOC_MODULE", "*", conds, suffix);
        }
        ArrayList<ApidocModule> al = new ArrayList<ApidocModule>();
        while (rs.next()) {
            ApidocModule info = new ApidocModule();
            setProperties(info, rs);
            al.add(info);
        }
        return al;
    }
    
    public static void setProperties(ApidocModule info, RecordSet rs){
        info.setStModuleId(rs.getOriginalString("ST_MODULE_ID"));
        info.setStModuleName(rs.getOriginalString("ST_MODULE_NAME"));
        info.setStRemark(rs.getOriginalString("ST_REMARK"));
        info.setStProjectId(rs.getOriginalString("ST_PROJECT_ID"));
        info.setNmOrder(rs.getBigDecimal("NM_ORDER"));
        info.setStParentId(rs.getOriginalString("ST_PARENT_ID"));
        info.setDtCreate(rs.getTimestamp("DT_CREATE"));
        info.setStExt1(rs.getOriginalString("ST_EXT1"));
        info.setStExt2(rs.getOriginalString("ST_EXT2"));
    }

	public ApidocModule get(String stModuleId) {
        Conditions conds = Conditions.newAndConditions();
        conds.add(new Condition("ST_MODULE_ID", Condition.OT_EQUAL, stModuleId));
        List<ApidocModule> list = query(conds, null);
        return list.size() > 0 ? list.get(0) : null;
    }
}
