INSERT INTO SMS_USER(ST_USER_ID,ST_LOGIN_NAME,ST_USER_CODE,ST_USER_NAME,ST_PASSWORD) VALUES ('coral', 'coral', 'coral', 'coral', 'efae4851800b5b135797bb71b6ef4deb');
INSERT INTO SMS_USER(ST_USER_ID,ST_LOGIN_NAME,ST_USER_CODE,ST_USER_NAME,ST_PASSWORD) VALUES ('admin', 'admin', 'admin', '超级用户', '9fec80fbcee7632ce78d1586332b299e');
INSERT INTO SMS_ROLE(ST_ROLE_ID,ST_ROLE_CODE,ST_ROLE_NAME) VALUES ('admin', 'admin','管理员');
INSERT INTO SMS_USER_ROLE(ST_ROLE_ID,ST_USER_ID,NM_ORDER) VALUES ('admin', 'coral',1);
INSERT INTO SMS_USER_ROLE(ST_ROLE_ID,ST_USER_ID,NM_ORDER) VALUES ('admin', 'admin',1);
